config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :calculations

  root to: 'calculations#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calculation.rb
class Calculation < ApplicationRecord
  validates :base, presence: true
  validates :target, presence: true
  validates :amount, numericality: {only_float: true}
  validates :wait_time, inclusion: { in: 1..250 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :timeoutable, timeout_in: 15.minutes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :show_flash

  private

  def show_flash
    flash.now[:notice] = 'Found the about page!' if request.path == '/pages/about'
  end
end

app/controllers/calculations_controller.rb
class CalculationsController < ApplicationController
  include CalculationsHelper
  before_action :authenticate_user!
  before_action :all_calculations, :only => [:index, :new, :edit]

  def index
    redirect_to new_calculation_path
  end

  def new
    @calculation = Calculation.new
  end

  def edit
    @calculation = Calculation.find(params[:id])
    render action: 'new'
  end

  def show
    @calculation = Calculation.find(params[:id])
    return unless @calculation

    @data = []
    todays_exchange = 0

    # loop for inserted "wait_time" times
    @calculation.wait_time.times do |time|
      date = Time.now - time.weeks
      rate = get_rate(date.beginning_of_week.strftime('%F'),
                      @calculation.base, @calculation.target)

      # Finding todays exchange amount for calculating profit/loss
      todays_exchange = rate * @calculation.amount.to_f if todays_exchange.zero?

      @data << {
          'week' => date.strftime('%U').to_i,
          'year' => date.year, 'id' => time,
          'rate' => rate, 'week_ago' => week_ago_text(time), 'rank' => '',
          'exchange_amount' => (@calculation.amount.to_f * rate.to_f).round(2),
          'profit_loss' => ((@calculation.amount.to_f * rate.to_f) - todays_exchange.to_f).round(2)
      }
    end

    @data = find_rank(@data)
    @graph_data = data_to_graph_format(@data)
  end

  def create
    @calculation = Calculation.new(calculation_params)
    if @calculation.save
      redirect_to @calculation
    else
      flash[:error] = @calculation.errors.full_messages.first
      render action: 'new'
    end
  end

  def update
    @calculation = Calculation.new(calculation_params)
    if @calculation.save
      redirect_to @calculation
    else
      flash[:error] = @calculation.errors.full_messages.first
      render action: 'new'
    end
  end

  def destroy
    @calculation = Calculation.find(params[:id])
    @calculation.destroy
    respond_to do |format|
      format.html { redirect_to new_calculation_path }
      format.xml  { head :ok }
    end
  end

  private

  def calculation_params
    params.require(:calculation).permit(:base, :target, :amount, :wait_time)
  end

  def all_calculations
    @calculations ||= Calculation.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calculations_helper.rb
require 'rest_client'
require 'json'
require 'date'

module CalculationsHelper

  API_BASE_URL = 'http://api.fixer.io/'

  # gets exchange rate for iserted date from fixer.io api
  def get_rate(date, base, target)
    uri = make_uri(date, base, target)
    data = get_cached_data(uri)
    data['rates'][target]
  end

  def find_rank(data)
    sorted_data = sort_by_rank(data)
    3.times do |rank|
      sorted_data[rank]['rank'] = rank + 1
    end
    sort_by_week(sorted_data)
  end

  def week_ago_text(week)
    if week == 0
      'this week'
    elsif week == 1
      '1 week ago'
    else
      "#{week} weeks ago"
    end
  end

  def data_to_graph_format(data)
    graph = {}
    data.each do |week|
      graph[week['year'].to_s + ' / ' + week['week'].to_s] = week['profit_loss']
    end
    graph
  end

  protected

  # saves querys in Cache for 24 hours
  def get_cached_data(uri)
    Rails.cache.fetch(uri, {expires_in: 24.hours, raw: true}) { JSON.parse(RestClient::Resource.new(uri).get) }
  end

  def make_uri(date, base, target)
    API_BASE_URL + date.to_s + '?' + {
        'base' => base,
        'symbols' => target
    }.to_query
  end

  def sort_by_rank(data)
    data.sort {|a,b| b['profit_loss'] <=> a['profit_loss']}
  end

  def sort_by_week(data)
    data.sort {|a,b| a['id'] <=> b['id']}
  end
end

app/views/calculations/new.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" href="#new" role="tab" data-toggle="tab">New calculation</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#show" role="tab" data-toggle="tab">All calculations</a>
  </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div role="tabpanel" class="tab-pane fade in active show" id="new">
    <div class='jumbotron'>
      <h2 >Best possible time for converting money from one currency to another</h2>
      <p class='lead'>
        <%= form_for @calculation, :html => {:class => 'form-horizontal center'} do |f| %>
          <div class='form-group'>
            <%= f.label :base, 'Base currency:', class: 'col-md-4 control-label' %>
            <div class='col-md-2'>
              <%= f.select :base, options_for_select([['AUD', 'AUD'], ['BGN', 'BGN'], ['BRL', 'BRL'],
                                                      ['CAD', 'CAD'], ['CHF', 'CHF'], ['CNY', 'CNY'],
                                                      ['CZK', 'CZK'], ['DKK', 'DKK'], ['EUR', 'EUR'],
                                                      ['GBP', 'GBP'], ['HKD', 'HKD'], ['HRK', 'HRK'],
                                                      ['HUF', 'HUF'], ['IDR', 'IDR'], ['ILS', 'ILS'],
                                                      ['INR', 'INR'], ['USD', 'USD']], @calculation.base), {}, {class: 'form-control'} %>
            </div>
          </div>
          <div class='form-group'>
            <%= f.label :target, 'Target currency:', class: 'col-md-4 control-label' %>
            <div class='col-md-2'>
              <%= f.select :target, options_for_select([['AUD', 'AUD'], ['BGN', 'BGN'], ['BRL', 'BRL'],
                                                        ['CAD', 'CAD'], ['CHF', 'CHF'], ['CNY', 'CNY'],
                                                        ['CZK', 'CZK'], ['DKK', 'DKK'], ['EUR', 'EUR'],
                                                        ['GBP', 'GBP'], ['HKD', 'HKD'], ['HRK', 'HRK'],
                                                        ['HUF', 'HUF'], ['IDR', 'IDR'], ['ILS', 'ILS'],
                                                        ['INR', 'INR'], ['USD', 'USD']], @calculation.target), {}, {class: 'form-control'} %>
            </div>
          </div>
          <div class='form-group'>
            <%= f.label :amount, 'Amount:', class: 'col-md-4 control-label' %>
            <div class='col-md-3'>
              <%= f.text_field :amount, class: 'form-control', :value => (number_with_precision(f.object.amount, :precision => 2) || 0) %>
            </div>
          </div>
          <div class='form-group'>
            <%= f.label :wait_time, 'Max. waiting time:', class: 'col-md-4 control-label' %>
            <div class='col-md-4'>
              <%= f.number_field :wait_time, class: 'form-control' %>
            </div>
          </div>
          <div class='form-group'>
            <div class='col-md-4'>
              <%= f.submit 'Calculate', class: 'btn btn-default btn-primary' %>
            </div>
          </div>
      <% end %>
      </p>
    </div>
  </div>
  <div role='tabpanel' class='tab-pane fade' id='show'>
    <table class=" table table-striped sortable">
      <thead>
      <tr>
        <th>Base</th>
        <th>Target</th>
        <th>Amount</th>
        <th>Wait time</th>
        <th>Created date</th>
        <th>Edit</th>
      </tr>
      </thead>

      <tbody>
      <% @calculations.each do |calculation| %>
          <tr>
            <td><%= calculation.base %></td>
            <td><%= calculation.target %></td>
            <td><%= calculation.amount.to_s %></td>
            <th><%= calculation.wait_time.to_s %></th>
            <th><%= calculation.created_at.to_s %></th>
            <th><%= link_to 'Edit', edit_calculation_path(calculation), :class => 'mark-button' %>
              / <%= link_to 'Delete', calculation_path(calculation),
                            data: {:confirm => 'Are you sure?'}, :method => :delete, :class => 'mark-button' %></th>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/calculations/show.html.erb
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" href="#table" role="tab" data-toggle="tab">Table</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#graph" role="tab" data-toggle="tab">Graph</a>
  </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div role="tabpanel" class="tab-pane fade in active show" id="table">
    <br>
    <h4>Amount that is going to be converted: <%= @calculation.amount.to_f.round(2).to_s %> <%= @calculation.base.to_s %></h4>
    <br>

    <table class=" table table-striped sortable">
      <thead>
      <tr>
        <th>Year / week</th>
        <th>Rate</th>
        <th>Exchanged amount</th>
        <th>Profit/Loss</th>
        <th>Rank</th>
      </tr>
      </thead>

      <tbody>
      <% @data.each do |week| %>
          <tr>
            <td><%= week['year'].to_s %> / <%= week['week'].to_s %> - (<%= week['week_ago'].to_s %>)</td>
            <td><%= week['rate'].to_s %></td>
            <td><%= week['exchange_amount'].to_s %> <%= @calculation.target.to_s %></td>
            <th><%= week['profit_loss'].to_s %> <%= @calculation.target.to_s %></th>
            <th><%= week['rank'].to_s %></th>
          </tr>
      <% end %>
      </tbody>
    </table>

  </div>
  <div role='tabpanel' class='tab-pane fade' id='graph'>
    <br>
    <%= line_chart(@graph_data) %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-dark bg-inverse">
    <% if user_signed_in? %>
        <li>
          <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
        </li>
    <% else %>
        <li>
          <%= link_to('Login', new_user_session_path)  %>
        </li>
    <% end %>
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to 'Rails bootstrap', root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'About', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jarmo Rails bootstrap</title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : 'Rails Bootstrap' %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'Chart.bundle', 'chartkick', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>